services:
  api:
    build: .
    container_name: api
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env

  app_logs:
    build: .
    container_name: app_logs
    command: ["python", "scripts.log_app.py"]
    env_file:
      - .env
    depends_on:
      - api