name: Continuos Integration

on: push

jobs:
  continuos-Integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Rodar Testes
        run: pytest